# Generated by Django 3.2.7 on 2022-01-13 14:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0002_auto_20220113_1347'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Article',
        ),
    ]
