# Generated by Django 3.2.7 on 2022-01-13 14:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0003_delete_article'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='new',
            name='date_of_pub',
        ),
        migrations.RemoveField(
            model_name='new',
            name='slug',
        ),
    ]
