# Generated by Django 3.2.7 on 2022-01-16 13:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0004_auto_20220113_1530'),
    ]

    operations = [
        migrations.AddField(
            model_name='new',
            name='date_of_pub',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='new',
            name='slug',
            field=models.SlugField(blank=True, max_length=128, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='new',
            name='text',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='new',
            name='title',
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
    ]
