# Generated by Django 3.2.7 on 2022-01-16 20:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0005_auto_20220116_1425'),
    ]

    operations = [
        migrations.AlterField(
            model_name='new',
            name='text',
            field=models.TextField(blank=True, max_length=356, null=True),
        ),
    ]
