# Generated by Django 4.0 on 2022-02-01 15:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0006_alter_new_text'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='new',
            options={'ordering': ['-date_of_pub'], 'verbose_name': 'New', 'verbose_name_plural': 'News'},
        ),
    ]
